[project]
name = "botoeducationtest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "uvicorn>=0.34.0",
    "fastapi[standard]>=0.115.6",
    "pytest>=8.3.3",
]
